### ISSUE TITLE
Form for website cannot be changed if server_name was not filled in

### ISSUE THREAD

**Issue by stucki** [snowflakecloud/api-frontend#4]
1. Create a new website, leave "server_name" empty
2. Save and open again
3. A Javascript error shows up and the form cannot be edited anymore

Solution: Default value for server_name must be "" not NULL
Workaround: `$ curl -v --user "username:password" -X GET "https://.../website/update/12?server_name=abc.example.local"`

**Comment by joeloare** [comment]
[Fixed](https://github.com/snowflakecloud/api-frontend/commit/d685c37e6a96116843a8574a80986c551fecd8c1)
