### ISSUE TITLE
Database cannot be removed

### ISSUE THREAD

**Issue by stucki** [snowflakecloud/api-frontend#7]
By default, no database is added to a website. The frontend form allows to choose between "mysql" and "postgresql". Once that you select one of these two values, it is no longer possible to disable this selection.

To be discussed:
- should it be possible to remove a database from the web hosting?
- if a database is removed from the record, will this delete the real database?
- if a database is removed from the record, will this delete the username and password?
- should it be possible to add more than 1 database to a website?

**Comment by joeloare** [comment]
Fixed by adding absent database type: [commit](https://github.com/snowflakecloud/api-frontend/commit/c3283cf749f9d749eb81f21bc6124b9b1ddddd86)
